### ISSUE TITLE
Comments not working on release 1.1.4

### ISSUE THREAD

**Issue by tranKILL** [framasoft/framadate#69]
Someone achieve to make comments working ?
When I click on submit nothing happens and no error in script..
The rest is ok ;)

Example url : https://coopeco-supermarche.be/framadate/studs.php?poll=WvYNfXwuS6r4jEKm&user=Nicolas%20Jourdain&id=189

Have a nice day

**Comment by tcitworld** [comment]
Hi @tranKILL 

Testing on your instance, it seems there's a database issue. 
```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in /home/clients/db707f9af57d3bb4d26d00ef9bc565a5/web/coopeco/framadate/app/classes/Framadate/Repositories/CommentRepository.php:30 

Stack trace: 
#0 /home/clients/db707f9af57d3bb4d26d00ef9bc565a5/web/coopeco/framadate/app/classes/Framadate/Repositories/CommentRepository.php(30): PDOStatement->execute(Array)
#1 /home/clients/db707f9af57d3bb4d26d00ef9bc565a5/web/coopeco/framadate/app/classes/Framadate/Services/PollService.php(163): Framadate\Repositories\CommentRepository->insert('WvYNfXwuS6r4jEK...', 'tcit', 'test') 
#2 /home/clients/db707f9af57d3bb4d26d00ef9bc565a5/web/coopeco/framadate/action/add_comment.php(78): Framadate\Services\PollService->addComment('WvYNfXwuS6r4jEK...', 'tcit', 'test') 
#3 {main} thrown in /home/clients/db707f9af57d3bb4d26d00ef9bc565a5/web/coopeco/framadate/app/classes/Framadate/Repositories/CommentRepository.php on line 30
```

I'll try reproducing and debugging this.

P.S : Please use https://framagit.org/framasoft/framadate/issues next time. :)

**Comment by tcitworld** [comment]
Moved to https://framagit.org/framasoft/framadate/issues/345

**Comment by tcitworld** [comment]
Hi @tranKILL, I made some comments on the issue at https://framagit.org/framasoft/framadate/issues/345
